package de.terminatorng.nastyores.datagen

import de.terminatorng.nastyores.init.ModBlocks
import net.fabricmc.fabric.api.datagen.v1.FabricDataGenerator
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider
import net.fabricmc.fabric.api.tag.convention.v1.ConventionalBlockTags
import net.minecraft.tag.BlockTags

class ModBlockTagProvider(dataGenerator: FabricDataGenerator?): FabricTagProvider.BlockTagProvider(dataGenerator) {

    override fun generateTags() {
        getOrCreateTagBuilder(ConventionalBlockTags.ORES).add(
            ModBlocks.AMADEUM_ORE,
            ModBlocks.APPETITE_ORE,
            ModBlocks.BALANCIUM_ORE,
            ModBlocks.BARELY_GENERITE_ORE,
            ModBlocks.BREAKIUM_ORE,
            ModBlocks.CRAPPIUM_ORE,
            ModBlocks.CRASHIUM_ORE,
            ModBlocks.ENDERITE_ORE,
            ModBlocks.EXPLODEMITE_ORE,
            ModBlocks.GHOSTIUM_ORE,
            ModBlocks.IDLIKEABITE_ORE,
            ModBlocks.KAKKARITE_ORE,
            ModBlocks.KILLIUM_ORE,
            ModBlocks.LITE_ORE,
            ModBlocks.DIAMOND_ORE,
            ModBlocks.MARMITE_ORE,
            ModBlocks.METEORITE_ORE,
            ModBlocks.MISLEADIUM_ORE,
            ModBlocks.MOVIUM_ORE,
            ModBlocks.NOPIUM_ORE,
            ModBlocks.NOSLEEPTONITE_ORE,
            ModBlocks.PAINTITWHITE_ORE,
            ModBlocks.PANDAEMONIUM_ORE,
            ModBlocks.POLITE_ORE,
            ModBlocks.SHIFTIUM_ORE,
            ModBlocks.SMITE_ORE,
            ModBlocks.STONIUM_ORE,
            ModBlocks.STREETSCUM_ORE,
            ModBlocks.TAUNTUM_ORE,
            ModBlocks.UNOBTAINIUM_ORE,
            ModBlocks.USELESSIUM_ORE,
            ModBlocks.WANNAFITE_ORE,
            ModBlocks.WANTARITE_ORE,
            ModBlocks.WEBSITE_ORE,
            ModBlocks.ZOMBIEUNITE_ORE,
        )

        getOrCreateTagBuilder(BlockTags.NEEDS_STONE_TOOL).add(
            ModBlocks.AMADEUM_ORE,
            ModBlocks.BALANCIUM_ORE,
            ModBlocks.BARELY_GENERITE_ORE,
            ModBlocks.BREAKIUM_ORE,
            ModBlocks.CRAPPIUM_ORE,
            ModBlocks.CRASHIUM_ORE,
            ModBlocks.ENDERITE_ORE,
            ModBlocks.EXPLODEMITE_ORE,
            ModBlocks.GHOSTIUM_ORE,
            ModBlocks.KAKKARITE_ORE,
            ModBlocks.KILLIUM_ORE,
            ModBlocks.LITE_ORE,
            ModBlocks.DIAMOND_ORE,
            ModBlocks.METEORITE_ORE,
            ModBlocks.MISLEADIUM_ORE,
            ModBlocks.MOVIUM_ORE,
            ModBlocks.NOPIUM_ORE,
            ModBlocks.NOSLEEPTONITE_ORE,
            ModBlocks.PANDAEMONIUM_ORE,
            ModBlocks.POLITE_ORE,
            ModBlocks.SHIFTIUM_ORE,
            ModBlocks.SMITE_ORE,
            ModBlocks.STREETSCUM_ORE,
            ModBlocks.TAUNTUM_ORE,
            ModBlocks.UNOBTAINIUM_ORE,
            ModBlocks.USELESSIUM_ORE,
            ModBlocks.WANNAFITE_ORE,
            ModBlocks.WANTARITE_ORE,
            ModBlocks.WEBSITE_ORE,
            ModBlocks.ZOMBIEUNITE_ORE,
        ).add(
            ModBlocks.AMADEUM_BLOCK,
            ModBlocks.BARELY_GENERITE_BLOCK,
            ModBlocks.CRAPPIUM_BLOCK,
            ModBlocks.CRASHIUM_BLOCK,
            ModBlocks.ENDERITE_BLOCK,
            ModBlocks.KAKKARITE_BLOCK,
            ModBlocks.DIAMOND_BLOCK,
            ModBlocks.MARMITE_BLOCK,
            ModBlocks.NOPIUM_BLOCK,
            ModBlocks.NOSLEEPTONITE_BLOCK,
            ModBlocks.POLITE_BLOCK,
            ModBlocks.SMITE_BLOCK,
        )

        getOrCreateTagBuilder(BlockTags.SHOVEL_MINEABLE).add(
            ModBlocks.APPETITE_ORE,
            ModBlocks.IDLIKEABITE_ORE,
            ModBlocks.MARMITE_ORE,
            ModBlocks.PAINTITWHITE_ORE,
        )

        getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE).add(
            ModBlocks.AMADEUM_ORE,
            ModBlocks.BALANCIUM_ORE,
            ModBlocks.BARELY_GENERITE_ORE,
            ModBlocks.BREAKIUM_ORE,
            ModBlocks.CRAPPIUM_ORE,
            ModBlocks.CRASHIUM_ORE,
            ModBlocks.ENDERITE_ORE,
            ModBlocks.EXPLODEMITE_ORE,
            ModBlocks.GHOSTIUM_ORE,
            ModBlocks.KAKKARITE_ORE,
            ModBlocks.KILLIUM_ORE,
            ModBlocks.LITE_ORE,
            ModBlocks.DIAMOND_ORE,
            ModBlocks.METEORITE_ORE,
            ModBlocks.MISLEADIUM_ORE,
            ModBlocks.MOVIUM_ORE,
            ModBlocks.NOPIUM_ORE,
            ModBlocks.NOSLEEPTONITE_ORE,
            ModBlocks.PANDAEMONIUM_ORE,
            ModBlocks.POLITE_ORE,
            ModBlocks.SHIFTIUM_ORE,
            ModBlocks.SMITE_ORE,
            ModBlocks.STONIUM_ORE,
            ModBlocks.STREETSCUM_ORE,
            ModBlocks.TAUNTUM_ORE,
            ModBlocks.UNOBTAINIUM_ORE,
            ModBlocks.USELESSIUM_ORE,
            ModBlocks.WANNAFITE_ORE,
            ModBlocks.WANTARITE_ORE,
            ModBlocks.WEBSITE_ORE,
            ModBlocks.ZOMBIEUNITE_ORE,
        ).add(
            ModBlocks.AMADEUM_BLOCK,
            ModBlocks.BARELY_GENERITE_BLOCK,
            ModBlocks.CRAPPIUM_BLOCK,
            ModBlocks.CRASHIUM_BLOCK,
            ModBlocks.ENDERITE_BLOCK,
            ModBlocks.KAKKARITE_BLOCK,
            ModBlocks.DIAMOND_BLOCK,
            ModBlocks.MARMITE_BLOCK,
            ModBlocks.NOPIUM_BLOCK,
            ModBlocks.NOSLEEPTONITE_BLOCK,
            ModBlocks.POLITE_BLOCK,
            ModBlocks.SMITE_BLOCK,
        )
    }

}